export {default as Navbar} from "./Navbar/Navbar"
export {default as Details} from "./Details/Details"
export {default as Footer} from "./Footer"
export { default as SignIn} from "./SignIn/SignIn"
export {default as SignUp} from "./SignUp/SignUp"
export {default as Sidebar} from "./Sidebar/Sidebar"
export {default as PastOrders} from "./PastOrders/PastOrders"
export {default as CreateOrder} from "./CreateOrder/CreateOrder"
export {default as Summary} from "./Summary/Summary"
export {default as Successful} from "./Popups/Successful"
export {default as Product} from "../components/Product"
export {default as CancelOrder} from "./Popups/CancelOrder"
export {default as NavbarSuccess} from "./NavbarSuccess/NavbarSuccess"
export {default as EachOrder} from "./EachOrder" 
export {default as CancelSummary} from "./CancelSummary/CancelSummary"
